### PR TITLE
lesson_1_4_no hardcode tasks and  save each task after click on submit bin 

### PR DESCRIPTION
**Pull request by gmax3000**
Lifting states and props handling

### CODE REVIEW

**Comment by xjqiu28** [comment]
Good job!! Here are some recommended changes:

1) In your handleTitleChange function in AddTodoForm.jsx, I see that you are missing a variable named newTodoTitle (requested from the homework as well). I see that you just directly passed in event.target.value into your setTodoTitle, which is not a bad thing, but keeping it in a variable can make the code more understandable (imagine if longer code base) and reusable.

Example:
let's say a company has 10,000 lines of code and all of a sudden there is just an event.target.value inside. Without any context, would you be able to tell on the spot what that particular line does or would it be easier if it said newTodoTitle?

Other than that, everything seems to be working and is good. 😄

**Comment by gmax3000** [comment]
Try to updated based on your comments. Please let me know if you have any question

**Comment by xjqiu28** [comment]
I think, there was some misunderstanding on my comment:

You actually made the changes in the wrong function, u changed handleAddTodo instead of handleTitleChange. I wanted you to add const newTodoTitle = event.target.value; and then in your setter, u just pass in setTodoTItle(newTodoTitle);

so the code would look like this:
`const handleTitleChange = (event) => {
    const newTodoTitle = event.target.value;
    setTodoTitle(newTodoTitle);
  };`
  
  you can change your handleAddTodo function back to how it was

**Comment by gmax3000** [comment]
i did changes from you last comment

**Pull request merged**
